---
title: "Sistemes Operatius"
tbl-colwidths: [5,5,5,30,5,5,5,5,5,30]
format:
    html:
        toc: false
---

## Planificaci贸

A continuaci贸 es presenta un calendari complet dels temes, el contingut del curs i les tasques per al semestre. Tingueu en compte que aquest calendari 茅s un document viu i es pot actualitzar. Tots els canvis es publicaran aqu铆 per assegurar-vos que teniu la informaci贸 m茅s actual.

::: column-screen-inset-right
| Setmana | Tipus              | Data       | Tema                                                     | Diapositives | Apunts | Laboratori | Altres | Tasques | Lliuraments  |                                                                                                                                       |
|:----:|:------------------:|:----------:|:---------------------------------------------------------|:--:|:--:|:--:|:--:|:--:|:----------------------------------------------------------------------------------------------------------------------------------------:|
| 1    | Teoria             |09/09/25    | **Unitat 01**: Introducci贸   | [](../slides/01-introduction.html#prepare){aria-label="Introducci贸"}  | [](../notes/01-introduction.html#prepare)   |  |  |        |  
| 1    | Laboratori         |10/09/25    | **Unitat 01**: Virtualitzaci贸 i Control de Versions   | [](../labs/01-lab-introduction.html#prepare)   |  | [](../labs/01-introduction/lab01.html#prepare) [](../labs/01-introduction/lab02.html#prepare) [](../labs/01-introduction/lab03.html#prepare) [](../labs/01-introduction/lab04.html#prepare) [](../labs/01-introduction/lab05.html#prepare) |        | 
| 2    | Teoria             |16/09/25    | **Unitat 01**: Introducci贸 a la programaci贸 de Sistema (I) (C)   | [](../slides/01-c.html#prepare)  |  [](../activities/unit00/02-ex01-c.qmd) |  |   |  [烩](../activities/unit00/03-ex02-c.qmd)     | 
| 3    | Teoria/Laboratori  |22/09/25    | **Unitat 02**: Kernel de Linux   | [](../slides/02-kernel.html#prepare)   |  | [](../labs/02-c-pointers/lab01.html#prepare)  |      |  
| 3   | Laboratori         |24/09/25    | **Unitat 02**: Crides a sistema   | [](../slides/02-syscalls.html#prepare)   |  | [](../labs/03-syscalls/lab01.qmd) [](../labs/03-syscalls/lab02.qmd)[烩](../activities/unit00/01-debianbin.qmd)   |      |[烩](../activities/unit01/01-kernel.qmd) | 
| 4    | Laboratori  |29/09/25    | **Unitat 02**: Kernel de Linux   |   |  | [](../labs/04-kernel/lab01.qmd) [](../labs/04-kernel/lab02.qmd) |      |
| 4    | Teoria/Laboratori  |01/10/25    | **Unitat 03**: Processos   | [](../slides/03-procs.html#prepare)   |  |  |     | [](../projects/project01.qmd) | |
| 5    | Teoria  |06/10/25    | **Unitat 03**: Creaci贸 de Processos   | [](../slides/03-create.html#prepare)   |   |  |     |    [烩](../activities/unit02/01-create.qmd)    |
| 5    | Teoria/Laboratori  |08/10/25    | **Unitat 03**: Senyals   |  [](../slides/03-signals.html#prepare) | [烩](../notes/03-process.qmd) |  |      | 


::: 